<a href="https://colab.research.google.com/github/LucasFreitas98/Data-Science/blob/main/redes_neurais_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Redes Neurais: Deep Learning com PyTorch**

In [ ]:
Problema de XOR

In [ ]:
Teorema da Aproximação Universal

In [1]:
import torch

In [7]:
lista = [[1,2,3],
         [4,5,6]]

tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)

tns = torch.FloatTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


# **Outras formas de instanciar tensores** 

A partir de arrays Numpy
torch.from_numpy()

In [9]:
import numpy as np

In [13]:
arr = np.random.rand(3,4)
arr = arr.astype(int)
tns = torch.from_numpy(arr)

print(arr)
print(arr.dtype)

print(tns)
print(tns.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int64
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
torch.int64


# Tensores inicializados 

Essas funções recebem como parâmetro o tamanho de cada dimensão do tensor. Aqui vamos conhecer as seguintes funções:

* torch.ones()  -> Cria um tensor preenchido com zeros
* torch.zeros() -> Cria um tensor preenchido com uns.
* torch.randn() -> Cria um tensor preenchido com números aleatórios a partir de uma distribuição normal.

In [14]:
tns1 = torch.ones(2,3)
tns0 = torch.zeros(4,5)
tnsr = torch.randn(3,3)

print(tns1)
print(tns0)
print(tnsr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 2.2487,  0.2549,  0.4276],
        [ 0.8700,  1.1518, -0.3327],
        [-0.8946, -0.0183, -0.9592]])


# **Tensor para array numpy**

In [17]:
print(type(tnsr))
arr = tnsr.data.numpy()
print(arr)
print(type(arr))

<class 'torch.Tensor'>
[[ 2.248722    0.2549236   0.42763343]
 [ 0.86995506  1.1518354  -0.33271855]
 [-0.89463603 -0.01834082 -0.95919   ]]
<class 'numpy.ndarray'>


# **Indexação**

De posse dessa informação, a indexação é feita de forma similar a arrays Numpy, através da sintaxe de colchetes [].

In [23]:
print(tnsr)
tnsr [0,2] = -10

print('')
print(tnsr)


print(tnsr[:, 2])

print(tnsr[0,2])

tensor([[  2.2487,   0.2549, -10.0000],
        [  0.8700,   1.1518,  -0.3327],
        [ -0.8946,  -0.0183,  -0.9592]])

tensor([[  2.2487,   0.2549, -10.0000],
        [  0.8700,   1.1518,  -0.3327],
        [ -0.8946,  -0.0183,  -0.9592]])
tensor([-10.0000,  -0.3327,  -0.9592])
tensor(-10.)


# **Operações com tensores**

A função .item() utilizada anteriormente extrai o número de um tensor que possui um único valor, permitido realizar as operações numéricas do Python. Caso o item não seja extraído, operações que envolvam tensores vão retornar novos tensores.

Vale ressaltar também que operações entre tensores são realizadas **ponto a ponto,** operando cada elemento (i, j) do tensor t1, com o elemento (i,j) do tensor t2.

In [32]:

tns = tnsr[0:2, :]
print(tns)
print(tns1)


#Para consulta o tamanho do tensor
print(tns.shape)
print(tns1.shape)

print(tns+tns1)
print(tns*tns1)
print(tns/tns1)


print(torch.mm(tns1,tns.T))

tensor([[  2.2487,   0.2549, -10.0000],
        [  0.8700,   1.1518,  -0.3327]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])
torch.Size([2, 3])
tensor([[ 3.2487,  1.2549, -9.0000],
        [ 1.8700,  2.1518,  0.6673]])
tensor([[  2.2487,   0.2549, -10.0000],
        [  0.8700,   1.1518,  -0.3327]])
tensor([[  2.2487,   0.2549, -10.0000],
        [  0.8700,   1.1518,  -0.3327]])
tensor([[-7.4964,  1.6891],
        [-7.4964,  1.6891]])


# **Função .size e .view()**

Uma operação **importantíssima** na manipulação de tensores para Deep Learning é a reorganização das suas dimensões. Dessa forma podemos, por exemplo, **linearizar um tensor n-dimensional.**

In [39]:
print(tns1.size())
print(tnsr.size())


tns = torch.randn(2,2,3)
print(tns)

print(tns.size())

torch.Size([2, 3])
torch.Size([3, 3])
tensor([[[ 0.4245,  0.1275, -0.1782],
         [ 0.3703,  0.1171,  0.6336]],

        [[-0.1074,  0.2096, -0.0808],
         [-1.8093,  0.0508, -1.1407]]])
torch.Size([2, 2, 3])


In [43]:
tns = tns.view(12)

tns = tns.view(tns.size(0), -1)
print(tns)

tensor([[ 0.4245],
        [ 0.1275],
        [-0.1782],
        [ 0.3703],
        [ 0.1171],
        [ 0.6336],
        [-0.1074],
        [ 0.2096],
        [-0.0808],
        [-1.8093],
        [ 0.0508],
        [-1.1407]])


# **GPU Cast**

Para que o seu script dê suporte a infraestrutura com e sem GPU, é importante definir o dispositivo no início do seu código de acordo com a verificação apresentada a seguir. Essa definição de dispositivo será utilizada toda vez que precisamos subir valores na GPU, como os pesos da rede, os gradientes

In [45]:
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
    device = torch.device('cpu')
print(device)

cpu
