<a href="https://colab.research.google.com/github/LucasFreitas98/Data-Science/blob/main/Redes_Neurais_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Redes Neurais: Deep Learning com PyTorch**

In [ ]:
Problema de XOR

In [ ]:
Teorema da Aproximação Universal

In [1]:
import torch

In [7]:
lista = [[1,2,3],
         [4,5,6]]

tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)

tns = torch.FloatTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


**Outras formas de instanciar tensores** 

A partir de arrays Numpy
torch.from_numpy()

In [9]:
import numpy as np

In [10]:
arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)

print(arr)
print(tns)

[[0.58662168 0.69854069 0.81630086 0.07022028]
 [0.62811871 0.55274319 0.245488   0.42053212]
 [0.72909683 0.89583554 0.03079496 0.62364722]]
tensor([[0.5866, 0.6985, 0.8163, 0.0702],
        [0.6281, 0.5527, 0.2455, 0.4205],
        [0.7291, 0.8958, 0.0308, 0.6236]], dtype=torch.float64)
